name: 02. Create Neon Project
on:
  workflow_dispatch:
    inputs:
      project-name:
        description: 'The name of the project to be created'
        required: true
        type: choice
        options: 
        - simple-asp-net-core-on-app-service-with-neon
permissions:
  id-token: write
  contents: read
env:
  LOCATION: westus3
jobs:
    create-neon-project-with-bicep:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region:  westus3
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          deploymentName: 'neon-project-${{ github.event.inputs.project-name }}'
          template: ./infrastructure/neon-project.bicep
          parameters: 'projectName=${{ github.event.inputs.project-name }}'
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear