name: 03. Simple ASP.NET Core on App Service
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
env:
  LOCATION: westeurope
  PROJECT_NAME: simple-asp-net-core-on-app-service-with-neon
jobs:
    deploy-infrastructure:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region:  ${{ env.LOCATION }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          deploymentName: simple-asp-net-core-on-app-service
          template: ./infrastructure/simple-asp-net-core-on-app-service.bicep
          parameters: 'location=${{ env.LOCATION }} projectName=${{ env.PROJECT_NAME }} neonConnectionString=${{ secrets.SIMPLE_ASPNET_CORE_ON_APP_SERVICE_NEON_CONNECTION_STRING }}'
          failOnStdErr: false
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear