name: Simple ASP.NET Core on App Service
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
    deploy-infrastructure:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region:  westeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          deploymentName: simple-asp-net-core-on-app-service
          template: ./infrastructure/simple-asp-net-core-on-app-service.bicep
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear